3DS:
  - '### Device\(s\)\s*.*3DS'

DS:
  - '### Device\(s\)\s*.*DS'

Wii U:
  - '### Device\(s\)\s*.*Wii U'

Wii:
  - '### Device\(s\)\s*.*Wii(\s{2,}|, )'

GameCube:
  - '### Device\(s\)\s*.*GameCube'

Switch:
  - '### Device\(s\)\s*.*Switch'

Vita:
  - '### Device\(s\)\s*.*Vita'

Web:
  - '### Device\(s\)\s*.*Web'

PS4:
  - '### Device\(s\)\s*.*PS4'
