if(TARGET windowing_interface)
    return()
endif()
add_library(windowing_interface INTERFACE)

include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/deps/add_dependency.cmake")
se_add_dependency(windowing_interface SDL3)

# compiler
if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT WEBOS)
	target_compile_definitions(windowing_interface PUBLIC USE_SDL3_POLLEVENT)
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
	target_compile_definitions(windowing_interface PUBLIC USE_SDL3_POLLEVENT)
elseif(CMAKE_SYSTEM_NAME STREQUAL "DragonFly")
	target_compile_definitions(windowing_interface PUBLIC USE_SDL3_POLLEVENT)
elseif(CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
	target_compile_definitions(windowing_interface PUBLIC USE_SDL3_POLLEVENT)
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
	target_compile_definitions(windowing_interface PUBLIC USE_SDL3_POLLEVENT)
elseif(CMAKE_SYSTEM_NAME STREQUAL "SunOS")
	target_compile_definitions(windowing_interface PUBLIC USE_SDL3_POLLEVENT)
endif()
