set(CATALOG_RECIPES
	libcurl:libcurl.cmake
	lua51:lua51.cmake
	sol2:sol2.cmake
	libdlgmod:libdlgmod.cmake
	ryuJS:ryujs.cmake
	plutovg:plutovg.cmake
	clay:clay.cmake
	nlohmann_json:nlohmann_json.cmake
)
