#include <cstdint>
#include <type_traits>

// An idea I had is to make a file that gets generated by the compiler that the interpreter can load directly
// without having to parse the json inside of the .sb3 file.
// The file would contain the bytecode and all other data needed to run the project.
// It would be a binary file and could be loaded directly into memory.
// This would make loading projects much faster and more efficient.

// However, I will probably finish it in a separate pull request once the new runtime is ready

struct BakedCostume {
    uint32_t nameStringOffset;
    uint32_t nameStringLen;
    int bitmapResolution;
    bool isSVG;
    double rotationCenterX;
    double rotationCenterY;
    uint32_t bitmaskOffset;
    uint32_t bitmaskCount;
};

struct BakedHatListener {
    uint16_t hatType;
    uint16_t eventParamId;
    uint32_t bytecodeOffset;
};

struct BakedTargetDefinition {
    uint32_t nameStringOffset;
    uint32_t nameStringLen;
    bool isStage;
    uint32_t index;

    uint32_t costumesStartIndex;
    uint32_t costumesCount;

    uint32_t bytecodeStartIndex;
    uint32_t bytecodeCount;

    uint32_t hatListenersStartIndex;
    uint32_t hatListenersCount;
};

// Absicherung
static_assert(std::is_trivially_copyable_v<BakedTargetDefinition>, "");
static_assert(std::is_trivially_copyable_v<BakedCostume>, "");