FROM gcc:14 AS main_builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake libmbedtls-dev libxcursor-dev libxi-dev libxrandr-dev libxss-dev libxtst-dev

COPY . .

# TODO: Fix SDL3 compatability in Dockerfile
RUN mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DSE_RENDERER=sdl2 && cmake --build . -j $(nproc)

FROM scratch AS exporter

COPY --from=main_builder /app/build/scratch-everywhere /
