FROM saschpe/android-ndk:36-jdk23.0.2_7-ndk30.0.14904198-cmake3.31.6 AS main_builder
WORKDIR /app

ARG ABIS="arm64-v8a,armeabi-v7a,x86,x86_64"
COPY . .

RUN cd android && ./gradlew assembleDebug -Pabis=${ABIS}

FROM scratch AS exporter
COPY --from=main_builder /app/android/app/build/outputs/apk/debug/scratch-android.apk /