FROM skylyrac/blocksds:slim-latest AS main_builder
WORKDIR /app

COPY . .

RUN make PLATFORM=nds -j ${nproc}

FROM scratch AS exporter
COPY --from=main_builder /app/build/nds/scratch-ds.nds /scratch-ds.nds
