FROM devkitpro/devkita64:latest AS main_builder
ENV CATALOG_NON_INTERACTIVE=1
ARG RENDERER=opengl_core
WORKDIR /app

RUN if [ "$RENDERER" = "opengl_core" ]; then \
        dkp-pacman -S --noconfirm switch-glad; \
    fi

COPY . .

RUN cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/cmake/Switch.cmake -DSE_RENDERER=${RENDERER} -B build-nx && cmake --build build-nx -j 2

FROM scratch AS exporter
COPY --from=main_builder /app/build-nx/scratch-nx.nro /
