FROM vitasdk/vitasdk:latest AS main_builder
WORKDIR /app

COPY . .

RUN cmake -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake -B build-vita && cmake --build build-vita -j $(nproc)

FROM scratch AS exporter

COPY --from=main_builder /app/build-vita/scratch-vita.vpk /
