FROM devkitpro/devkitppc:20260127 AS main_builder
WORKDIR /app

COPY . .

RUN /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -B build-wiiu -DCMAKE_BUILD_TYPE=Release -DSE_FORCE_CLOUDVARS_SOURCE_CURL=ON && cmake --build build-wiiu -j2 && cmake --build build-wiiu --target package_wiiu

FROM scratch AS exporter
COPY --from=main_builder /app/build-wiiu/scratch-wiiu.zip /
