# _____     ___ ____  
#  ____|   |    ____|   
# |     ___|   |____
#
FROM ps2dev/ps2dev:latest AS main_builder

RUN apk add --no-cache cmake make mpc1 mpfr4 gmp git

WORKDIR /app

COPY . .

RUN cmake -B build-ps2 -S . -DCMAKE_TOOLCHAIN_FILE=$PS2SDK/ps2dev.cmake -DCMAKE_BUILD_TYPE=Release && make -C build-ps2 -j 2

FROM scratch AS exporter

# TODO: change the .elf with whatever the PS2 expects later
COPY --from=main_builder /app/build-ps2/scratch-everywhere.elf /