#pragma once

#include <cstdint>

enum class HatType : uint16_t {
    FLAG_CLICKED,
    THIS_SPRITE_CLICKED,
    STAGE_CLICKED,
    BROADCAST_RECEIVED,
    KEY_PRESSED,
    BACKDROP_SWITCHED,
    GREATER_THAN,
    CLONE_START,
};

enum Opcode : uint16_t {
    YIELD,
    PUSH_POS_INT,
    PUSH_NEG_INT,
    PUSH_FALSE,
    PUSH_TRUE,
    PUSH_CONST,

    motion_movesteps,
    motion_goto,
    motion_goto_sprite,
    motion_goto_random,
    motion_goto_mouse,
    motion_gotoxy,
    motion_turnleft,
    motion_turnright,
    motion_pointindirection,
    motion_pointtowards,
    motion_pointtowards_sprite,
    motion_pointtowards_random,
    motion_pointtowards_mouse,
    motion_glidesecstoxy,
    motion_glideto,
    motion_glideto_sprite,
    motion_glideto_mouse,
    motion_glideto_random,
    motion_ifonedgebounce,
    motion_setrotationstyle_leftright,
    motion_setrotationstyle_allaround,
    motion_setrotationstyle_dontrotate,
    motion_xposition,
    motion_yposition,
    motion_direction,
    motion_setx,
    motion_sety,
    motion_changexby,
    motion_changeyby,
    motion_pointtowards_menu,

    operator_add,
    operator_subtract,
    operator_multiply,
    operator_divide,
    operator_random,
    operator_join,
    operator_letterof,
    operator_length,
    operator_mod,
    operator_round,
    operator_equals,
    operator_greater_than,
    operator_less_than,
    operator_and,
    operator_or,
    operator_not,
    operator_contains,
    operator_mathop_abs,
    operator_mathop_floor,
    operator_mathop_ceil,
    operator_mathop_sqrt,
    operator_mathop_sin,
    operator_mathop_cos,
    operator_mathop_tan,
    operator_mathop_asin,
    operator_mathop_acos,
    operator_mathop_atan,
    operator_mathop_ln,
    operator_mathop_log,
    operator_mathop_epow,
    operator_mathop_10pow,

    control_create_clone_of,
    control_create_clone_of_me,
    control_create_clone_of_other,
    control_delete_this_clone,
    control_stop_all,
    control_stop_other_scripts,
    control_wait,
    control_repeat,
    control_for_each,

    looks_say,
    looks_sayforsecs,
    looks_think,
    looks_thinkforsecs,
    looks_hide,
    looks_show,
    looks_switchcostumeto,
    looks_switchcostumeto_number,
    looks_nextcostume,
    looks_previouscostume,
    looks_switchbackdropto,
    looks_switchbackdropto_number,
    looks_nextbackdrop,
    looks_previousbackdrop,
    looks_switchbackdropto_andwait,
    looks_switchbackdropto_number_andwait,
    looks_nextbackdrop_andwait,
    looks_previousbackdrop_andwait,

    data_setvariableto_private,
    data_setvariableto_public,
    data_changevariableby_private,
    data_changevariableby_public,

    data_addtolist_private,
    data_addtolist_public,
    data_deleteoflist_private,
    data_deleteoflist_last_private,
    data_deleteoflist_random_private,
    data_deleteoflist_public,
    data_deleteoflist_last_public,
    data_deleteoflist_random_public,
    data_deletealloflist_private,
    data_deletealloflist_public,
    data_insertatlist_private,
    data_insertatlist_public,
    data_itemoflist_private,
    data_itemoflist_public,
    data_itemnumoflist_private,
    data_itemnumoflist_public,
    data_lengthoflist_private,
    data_lengthoflist_public,
    data_listcontainsitem_private,
    data_listcontainsitem_public,
    data_replaceitemoflist_private,
    data_replaceitemoflist_public,
    data_show,
    data_hide,

    sensing_timer,
    sensing_loudness,

    event_when_larger_then,
    event_broadcast,
    event_broadcast_dynamic,
    event_broadcastandwait,
    event_broadcastandwait_dynamic,
    RETURN,

    JUMP_FWD,
    JUMP_BACK,
    JUMP_FWD_IF_FALSE,
    JUMP_BACK_IF_FALSE,
    JUMP_ABS_32,
    PUSH_CALL_STACK,
    RETURN_WITH_VALUE,

    CALL_PROCEDURE,
    CALL_PROCEDURE_WOS,
    PUSH_PROC_ARG, // without screen refresh

    PUSH_PUB_VAR,
    PUSH_PRI_VAR,
    PUSH_PUB_LIST,
    PUSH_PRI_LIST,

    looks_costumenumbername_number,
    looks_costumenumbername_name,

    sound_playuntildone,
    sound_play,
    sound_stopallsounds,
    sound_setvolumeto,
    sound_changevolumeby,
    sound_volume,

    MAX_BLOCKS,
};