set(SE_DEFAULT_OUTPUT_NAME "scratch-dos")

set(SE_RENDERER_VALID_OPTIONS "")
set(SE_AUDIO_ENGINE_VALID_OPTIONS "")
set(SE_DEPS_VALID_OPTIONS "fallback" "system")

set(SE_CACHING_DEFAULT OFF)
set(SE_DECTALK_DEFAULT OFF)

set(SE_ALLOW_CMAKERC OFF)
set(SE_ALLOW_CLOUDVARS OFF)
set(SE_ALLOW_DOWNLOAD OFF)

set(SE_HAS_THREADS OFF)

set(SE_HAS_TOUCH FALSE)
set(SE_HAS_MOUSE TRUE)
set(SE_HAS_KEYBOARD TRUE)
set(SE_HAS_CONTROLLER FALSE)

set(SE_PLATFORM "dos")