set(SE_DEFAULT_OUTPUT_NAME "scratch-ios")

set(SE_RENDERER_VALID_OPTIONS "sdl2" "sdl3")
set(SE_AUDIO_ENGINE_VALID_OPTIONS "sdl2" "sdl3")
set(SE_DEPS_VALID_OPTIONS "source" "fallback" "system")

set(SE_CACHING_DEFAULT ON)
set(SE_CMAKERC_DEFAULT OFF)

set(SE_ALLOW_CMAKERC ON)
set(SE_ALLOW_CLOUDVARS OFF)
set(SE_ALLOW_CUSTOM_EXTENSIONS OFF)
set(SE_ALLOW_DOWNLOAD OFF)
set(SE_DECTALK ON)

set(SE_PLATFORM_DEFINITIONS "__IOS__")
set(SE_PLATFORM "ios")

set(SE_HAS_THREADS ON)

set(SE_HAS_TOUCH TRUE)
set(SE_HAS_MOUSE FALSE)
set(SE_HAS_KEYBOARD FALSE)
set(SE_HAS_CONTROLLER TRUE)
