set(SE_DEFAULT_OUTPUT_NAME "scratch-64")

set(SE_RENDERER_VALID_OPTIONS "headless")
set(SE_AUDIO_ENGINE_VALID_OPTIONS "n64")
set(SE_DEPS_VALID_OPTIONS "fallback" "system")

set(SE_CACHING_DEFAULT OFF)

set(SE_ALLOW_CMAKERC OFF)
set(SE_ALLOW_CLOUDVARS OFF)
set(SE_ALLOW_DOWNLOAD OFF)

set(SE_PLATFORM_DEFINITIONS "__N64__" "MIPS")
set(SE_PLATFORM "n64")

set(SE_HAS_THREADS OFF)

set(SE_HAS_TOUCH FALSE)
set(SE_HAS_MOUSE FALSE)
set(SE_HAS_KEYBOARD FALSE)
set(SE_HAS_CONTROLLER TRUE)