set(SE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(SE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
if(PROJECT_VERSION_PATCH)
	set(SE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
else()
	set(SE_VERSION_PATCH "0")
endif()

set(SE_GIT_COMMIT_HASH "unknown")
set(SE_GIT_DIRTY 1)
set(SE_VERSION_TYPE "SE_VERSION_TYPE_DEV")
set(SE_VERSION_DISPLAY "")

find_package(Git QUIET)

if(GIT_FOUND)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
		OUTPUT_VARIABLE SE_GIT_COMMIT_HASH
		OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE GIT_HASH_RESULT
		ERROR_QUIET
	)
	if(NOT GIT_HASH_RESULT EQUAL 0)
		set(SE_GIT_COMMIT_HASH "unknown")
	endif()

	execute_process(
		COMMAND "${GIT_EXECUTABLE}" log -1 --format=%s
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
		OUTPUT_VARIABLE SE_GIT_COMMIT_MSG
		OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE GIT_MSG_RESULT
		ERROR_QUIET
	)

	execute_process(
		COMMAND "${GIT_EXECUTABLE}" diff --quiet HEAD
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
		RESULT_VARIABLE GIT_DIFF_RESULT
		ERROR_QUIET
	)

	execute_process(
		COMMAND "${GIT_EXECUTABLE}" diff --quiet --cached HEAD
		WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
		RESULT_VARIABLE GIT_STAGED_RESULT
		ERROR_QUIET
	)

	if(GIT_DIFF_RESULT EQUAL 0 AND GIT_STAGED_RESULT EQUAL 0)
		set(SE_GIT_DIRTY 0)
	else()
		set(SE_GIT_DIRTY 1)
	endif()

	if(GIT_MSG_RESULT EQUAL 0)
		string(TOLOWER "${SE_GIT_COMMIT_MSG}" SE_GIT_COMMIT_MSG_LOWER)

		if(SE_GIT_COMMIT_MSG_LOWER MATCHES "^(release candidate|release|beta|alpha) ([0-9]+\\.[0-9]+(\\.[0-9]+)?)$")
			set(SE_COMMIT_PREFIX "${CMAKE_MATCH_1}")
			set(SE_VERSION_DISPLAY "${CMAKE_MATCH_2}")

			if(SE_COMMIT_PREFIX STREQUAL "release")
				set(SE_VERSION_TYPE "SE_VERSION_TYPE_RELEASE")
			elseif(SE_COMMIT_PREFIX STREQUAL "beta")
				set(SE_VERSION_TYPE "SE_VERSION_TYPE_BETA")
			elseif(SE_COMMIT_PREFIX STREQUAL "alpha")
				set(SE_VERSION_TYPE "SE_VERSION_TYPE_ALPHA")
			elseif(SE_COMMIT_PREFIX STREQUAL "release candidate")
				set(SE_VERSION_TYPE "SE_VERSION_TYPE_RELEASE_CANDIDATE")
			endif()
		elseif(SE_GIT_DIRTY EQUAL 0)
			set(SE_VERSION_TYPE "SE_VERSION_TYPE_NIGHTLY")
			set(SE_VERSION_DISPLAY "${SE_GIT_COMMIT_HASH}")
		else()
			set(SE_VERSION_TYPE "SE_VERSION_TYPE_DEV")
			set(SE_VERSION_DISPLAY "")
		endif()
	endif()
endif()

configure_file(
	"${CMAKE_CURRENT_SOURCE_DIR}/cmake/version_config.h.in"
	"${CMAKE_CURRENT_BINARY_DIR}/version_config.h"
	@ONLY
)

if(WIN32)
	set(SE_WINDOWS_GFX_DIR "${CMAKE_CURRENT_SOURCE_DIR}/gfx/windows")
	configure_file(
		"${CMAKE_CURRENT_SOURCE_DIR}/gfx/windows/resource.rc.in"
		"${CMAKE_CURRENT_BINARY_DIR}/resource.rc"
		@ONLY
	)
endif()
